### YamlMime:ModuleUnit
uid: learn.github.maintain-secure-repository-github.3-security-automation
title: Automated security
metadata:
  title: Automated security
  description: Learn about automated security features within GitHub.
  ms.date: 09/27/2021
  author: a-a-ron
  ms.author: aastewar
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 6
content: |
  [!include[](includes/3-security-automation.md)]