### YamlMime:ModuleUnit
uid: learn.configure-dependabot-security-updates-on-github-repo.dependabot-alerts
title: Dependabot alerts
metadata:
  unitType: learning-content
  title: Dependabot alerts
  description: This unit introduces Dependabot alerts and explains how they work.
  ms.date: 1/5/2022
  author: sterling463
  ms.author: csterling 
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 4
content: |
  [!include[](includes/3-dependabot-alerts.md)]