### YamlMime:ModuleUnit
uid: learn.github-administration-github-advanced-security.what-is-github-advanced-security
title: What is GitHub Advanced Security?
metadata:
  unitType: learning-content
  title: What is GitHub Advanced Security?
  description: Overview of the GitHub Advanced Security features and where they fit in the software development lifecycle
  ms.date: 2/14/2022
  author: lucie-docs
  ms.author: lucielenaour
  ms.topic: interactive-tutorial
  ms.prod: learning-azure # Edit as appropriate for your portfolio area
durationInMinutes: 3
content: |
  [!include[](includes/2-what-is-github-advanced-security.md)]
