### YamlMime:ModuleUnit
uid: learn.github-administration-github-advanced-security.enable-github-advanced-security
title: Enable GitHub Advanced Security
metadata:
  unitType: learning-content
  title: Enable GitHub Advanced Security
  description: Overview of how to enable GitHub Advanced Security on Enterprise Cloud and Enterprise Server
  ms.date: 2/14/2022
  author: lucie-docs
  ms.author: lucielenaour
  ms.topic: interactive-tutorial
  ms.prod: learning-azure # Edit as appropriate for your portfolio area
durationInMinutes: 5
content: |
  [!include[](includes/3-enable-github-advanced-security.md)]
